#!/bin/bash
# Lisbon Mac mini — headless boot audit + repair.
#
# Symptoms we are fixing:
#   - Mini boots in install zone but does NOT auto-login (greeted by login window).
#   - Wi-Fi never joins the venue SSID because the password lives in the
#     login keychain, which is locked until a user logs in.
#   - Operator has to walk over with a monitor + keyboard. Unacceptable.
#
# Run on the mini itself (or over SSH/Tailscale). It will:
#   1. Verify Tailscale system extension is up (your remote shell guarantee).
#   2. Ensure auto-login is fully wired (both name AND UID) for the install user.
#   3. Copy the venue Wi-Fi password from the login keychain to the System
#      keychain so the Wi-Fi daemon can read it pre-login.
#   4. Re-print the headless audit so you can confirm green.
#
# Idempotent. Safe to run repeatedly. Will prompt for sudo password once.
# Requires the operator to currently be logged in (so the login keychain is
# unlocked and we can read the SSID password without re-prompting).

set -euo pipefail

INSTALL_USER="${INSTALL_USER:-ganchitecture}"
VENUE_SSID="${VENUE_SSID:-Moodscape}"
WIFI_DEV="${WIFI_DEV:-en1}"

echo "== Lisbon mini headless setup =="
echo "user:      $INSTALL_USER"
echo "venue SSID: $VENUE_SSID"
echo "wifi dev:  $WIFI_DEV"
echo

INSTALL_UID="$(id -u "$INSTALL_USER")"
if [[ -z "$INSTALL_UID" ]]; then
  echo "FATAL: user $INSTALL_USER not found" >&2
  exit 1
fi

# Prime sudo once up front. Everything below uses cached credentials.
# In a non-TTY context (cron, automation) require sudo to already be primed
# or NOPASSWD; we cannot prompt.
if ! sudo -n true 2>/dev/null; then
  if ! sudo -v 2>/dev/null; then
    echo "FATAL: need sudo for autologin defaults and System keychain edits." >&2
    echo "       Run 'sudo -v' (and enter password) before invoking this script," >&2
    echo "       or invoke it directly: sudo $0" >&2
    exit 1
  fi
fi

# --- 1. Tailscale ----------------------------------------------------------
echo "--- Tailscale ---"
if pgrep -f "io.tailscale.ipn.macsys.network-extension" >/dev/null; then
  echo "ok: tailscale system extension is running (root, pre-login capable)"
else
  echo "WARN: tailscale system extension not detected. Open Tailscale.app once"
  echo "      while logged in, accept the system-extension prompt, sign in."
fi
/Applications/Tailscale.app/Contents/MacOS/Tailscale status --self=true --peers=false 2>/dev/null \
  | head -1 || echo "WARN: could not query tailscale status"
echo

# --- 2. Auto-login ---------------------------------------------------------
echo "--- Auto-login ---"
CUR_NAME="$(defaults read /Library/Preferences/com.apple.loginwindow autoLoginUser 2>/dev/null || true)"
CUR_UID="$(defaults read /Library/Preferences/com.apple.loginwindow autoLoginUserUID 2>/dev/null || true)"
FILEVAULT_STATE="$(fdesetup status 2>/dev/null | head -1)"
echo "current autoLoginUser    = ${CUR_NAME:-<unset>}"
echo "current autoLoginUserUID = ${CUR_UID:-<unset>}"
echo "FileVault                = $FILEVAULT_STATE"

if [[ "$FILEVAULT_STATE" == *"FileVault is On"* ]]; then
  echo "FATAL: FileVault is ON. Autologin is impossible until it is turned off." >&2
  echo "       Apple Menu -> System Settings -> Privacy & Security -> FileVault." >&2
  exit 2
fi

NEEDS_FIX=0
[[ "$CUR_NAME" != "$INSTALL_USER" ]] && NEEDS_FIX=1
[[ "$CUR_UID"  != "$INSTALL_UID"  ]] && NEEDS_FIX=1

if [[ "$NEEDS_FIX" == "1" ]]; then
  echo "fixing autologin (sudo prompt incoming)..."
  sudo defaults write /Library/Preferences/com.apple.loginwindow autoLoginUser "$INSTALL_USER"
  sudo defaults write /Library/Preferences/com.apple.loginwindow autoLoginUserUID -int "$INSTALL_UID"
  # /etc/kcpassword is regenerated by macOS when you toggle autologin in
  # System Settings; if it is missing the autologin will silently no-op.
  if [[ ! -f /etc/kcpassword ]]; then
    echo "WARN: /etc/kcpassword does not exist. Open System Settings ->"
    echo "      Users & Groups -> 'Automatically log in as' and re-select"
    echo "      $INSTALL_USER, entering your password once. macOS will"
    echo "      generate /etc/kcpassword and the cold-boot autologin will work."
  else
    echo "ok: /etc/kcpassword present ($(stat -f%Sm /etc/kcpassword))"
  fi
else
  echo "ok: autologin already configured correctly"
fi
echo

# --- 3. Wi-Fi credential placement ----------------------------------------
echo "--- Wi-Fi credential ($VENUE_SSID) ---"
SYSTEM_KEYCHAIN="/Library/Keychains/System.keychain"
if sudo security find-generic-password -l "$VENUE_SSID" "$SYSTEM_KEYCHAIN" >/dev/null 2>&1; then
  IN_SYSTEM=1
else
  IN_SYSTEM=0
fi
KEYCHAIN_LINE="$(security find-generic-password -l "$VENUE_SSID" 2>&1 | head -1 || true)"
echo "current keychain (default search) = $KEYCHAIN_LINE"
echo "present in System.keychain        = $IN_SYSTEM"

if [[ "$IN_SYSTEM" == "1" ]]; then
  # Verify it has a non-empty password — earlier attempts in this repo
  # accidentally created empty entries that look fine to listings.
  PW_LEN="$(sudo security find-generic-password -wa "$VENUE_SSID" "$SYSTEM_KEYCHAIN" 2>/dev/null | wc -c | tr -d ' ')"
  if [[ "${PW_LEN:-0}" -ge 2 ]]; then
    echo "ok: $VENUE_SSID password already lives in the System keychain (len=$PW_LEN)"
  else
    echo "WARN: $VENUE_SSID entry exists in System.keychain but password is empty."
    echo "      Delete and re-add manually:"
    echo "        sudo security delete-generic-password -a $VENUE_SSID -s AirPort $SYSTEM_KEYCHAIN"
    echo "        read -s \"MS?$VENUE_SSID password: \" && echo"
    echo "        sudo security add-generic-password -a $VENUE_SSID -s AirPort -A -w \"\$MS\" $SYSTEM_KEYCHAIN"
    echo "        unset MS"
  fi
else
  echo "moving $VENUE_SSID password into the System keychain..."
  if ! PW="$(security find-generic-password -wa "$VENUE_SSID" 2>/dev/null)"; then
    echo "FATAL: could not read $VENUE_SSID password from any unlocked keychain." >&2
    echo "       The login keychain is probably locked (common when SSHing in" >&2
    echo "       via Tailscale rather than sitting at the console)." >&2
    echo "" >&2
    echo "       Fix A: unlock the login keychain, then re-run this script:" >&2
    echo "         security unlock-keychain ~/Library/Keychains/login.keychain-db" >&2
    echo "" >&2
    echo "       Fix B: paste the password directly into the System keychain:" >&2
    echo "         sudo security add-generic-password \\" >&2
    echo "           -a $VENUE_SSID -s AirPort \\" >&2
    echo "           -w 'PASSWORD_HERE' -A \\" >&2
    echo "           /Library/Keychains/System.keychain" >&2
    exit 3
  fi
  if [[ -z "$PW" ]]; then
    echo "FATAL: read $VENUE_SSID entry but password is empty." >&2
    exit 4
  fi
  sudo security add-generic-password \
    -a "$VENUE_SSID" -s AirPort \
    -w "$PW" -A \
    /Library/Keychains/System.keychain
  unset PW
  echo "ok: $VENUE_SSID password installed to System.keychain"
fi
echo

# --- 4. Preferred-networks sanity -----------------------------------------
echo "--- Preferred networks (top wins) ---"
networksetup -listpreferredwirelessnetworks "$WIFI_DEV" 2>&1 | sed 's/^/  /'
echo

# --- 5. Service order -----------------------------------------------------
echo "--- Network service order (top wins when both up) ---"
networksetup -listnetworkserviceorder | grep -E "^\(" | sed 's/^/  /'
echo

echo "== done =="
echo "Final check: power-cycle the mini with NO monitor/keyboard attached."
echo "From bento, expect:"
echo "  - tailscale ping ganchi   (immediate, ethernet OR wifi)"
echo "  - ssh ganchitecture@ganchi  (after ~30s, autologin completed)"
